// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7yyN8DaKpWmuYPK8EJFTpxmCnSqn_tWk',
    appId: '1:160125943553:web:18b9a9be2388799c18e500',
    messagingSenderId: '160125943553',
    projectId: 'eseo-f394c',
    authDomain: 'eseo-f394c.firebaseapp.com',
    storageBucket: 'eseo-f394c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRtagTrgTDVUR2n9qETwMvOXk8mcVYrl4',
    appId: '1:160125943553:android:794e10286a30709e18e500',
    messagingSenderId: '160125943553',
    projectId: 'eseo-f394c',
    storageBucket: 'eseo-f394c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlTgOFvkbOs6qyWrPIg5q7YNo8oW5Cja4',
    appId: '1:160125943553:ios:389430699cade11c18e500',
    messagingSenderId: '160125943553',
    projectId: 'eseo-f394c',
    storageBucket: 'eseo-f394c.firebasestorage.app',
    androidClientId: '160125943553-7qr8ro5ru2ocs11g2ktpu7kvv20bksl6.apps.googleusercontent.com',
    iosClientId: '160125943553-c4cssb8kmng6hq0qqvgjt4c3pcmuu4jh.apps.googleusercontent.com',
    iosBundleId: 'com.example.eseoFlutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlTgOFvkbOs6qyWrPIg5q7YNo8oW5Cja4',
    appId: '1:160125943553:ios:389430699cade11c18e500',
    messagingSenderId: '160125943553',
    projectId: 'eseo-f394c',
    storageBucket: 'eseo-f394c.firebasestorage.app',
    androidClientId: '160125943553-7qr8ro5ru2ocs11g2ktpu7kvv20bksl6.apps.googleusercontent.com',
    iosClientId: '160125943553-c4cssb8kmng6hq0qqvgjt4c3pcmuu4jh.apps.googleusercontent.com',
    iosBundleId: 'com.example.eseoFlutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7yyN8DaKpWmuYPK8EJFTpxmCnSqn_tWk',
    appId: '1:160125943553:web:a46a63780ba5345018e500',
    messagingSenderId: '160125943553',
    projectId: 'eseo-f394c',
    authDomain: 'eseo-f394c.firebaseapp.com',
    storageBucket: 'eseo-f394c.firebasestorage.app',
  );

}